### ISSUE TITLE
Operands Could Not Be Broadcast Together With Shapes

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#103]
**Describe the bug**
Appears to be an unusual error found only with certain runs. Result is that said runs can be fetched but neither plotted nor fit.
When on the inspect tab (for example with run # 2018:45112) ... error is: _ValueError_ operands could not be broadcast together with shapes (1599,) (1600,)

"operands could not be broadcast together with shapes" 

**To Reproduce**
Steps to reproduce the behaviour:
1. Which runs were loaded: 45110-45126 (year = 2018)
2. Click on 'either attempt to plot or attempt to fit. Numerous runs fail to load normally.'
3. See error above

**Desktop (please complete the following information):**
 - Both linbnmr3 and muesli checked/tested
 - bfit Version [4.12.4]

**Additional context**
N/A

**Comment by dfujim** [comment]
Issue was with bdata. Please update bdata using `pip install --user --upgrade bdata`. I'll update muesli and linbnmr3.
