### ISSUE TITLE
JOSS review: citation for FastNumericalIntegration

### ISSUE THREAD

**Issue by jpata** [dfujim/bfit#106]
Given that externally-written source code such as [FastNumericalIntegration](https://github.com/dfujim/bfit/tree/master/bfit/fitting/FastNumericalIntegration_src) is packaged together with bfit and seems to be central to the functionality, it may be appropriate to also cite this software in the JOSS bfit paper.

**Comment by dfujim** [comment]
Added citation in 30adae4cfc799d803e3f634dddf51970c770bbc9

Thanks for the suggestion!
