### ISSUE TITLE
Problem toggling use of NBM counter in the Fetch tab

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bfit#107]
In the Fetch tab, toggling the use of NBM counters does not work as intended.

To reproduce, load Run 40434 from 2021 and try toggling the NBM selection in the menu. The displayed asymmetry is the same independent of whether the NBMs are used.

bfit version: 4.15.1

**Comment by dfujim** [comment]
Resolved in 7c0b982378a42d6d75e9cb672eddb4be57b6577d
