### ISSUE TITLE
[bug] magnetic field uncertainty

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bfit#112]
I don't think the uncertainty calculation for the magnetic field at the NQR stations is handled correctly.

For example, in:

https://github.com/dfujim/bfit/blob/2020ca88b1e79cd71f33bb6f104a4e202f5afed1/bfit/backend/fitdata.py#L1583-L1595

the field's uncertainty is estimated by passing the uncertainty of the magnet's current directly into `bfit.gui.calculator_nqr_B0_hh6.current2field_hh6` or`bfit.gui.calculator_nqr_B0_hh.current2field_hh`, which is quite different than using the usual expression for error propagation. Similarly, the uncertainty in the linear fit coefficients (from the field calibration curves) isn't accounted for at present. 

This is partially related to dfujim/bdata#9.

**Comment by dfujim** [comment]
Yes this is certainly not the best handling of errors here, most likely this solution was a placeholder which I subsequently forgot about. As you mentioned in dfujim/bdata#9, the conversion is likely best handled in bdata anyway.

**Comment by dfujim** [comment]
@rmlmcfadden I would like your opinion on this: I am generally unhappy with the standard error propagation equations for linear interpolation since the error becomes highly dependent on the position in x. I think a better estimate would be the RMS of the residuals (or perhaps a weighted RMS). What do you think?

**Comment by dfujim** [comment]
I ended up summing the RMS error and the converted stdev of the current in quadrature: 

https://github.com/dfujim/bfit/blob/1069667661e6afc0c30c1e49ac0f3120b6944460/bfit/backend/fitdata.py#L1589-L1598

I think this is ok? It seems like a mostly reasonable thing to do, but I haven't actually worked out the full details of what the calculation should be.

**Comment by rmlmcfadden** [comment]
Looks good to me!
