### ISSUE TITLE
Unable to export data files 

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#113]
![bfit_export_error_message](https://user-images.githubusercontent.com/52260777/207374725-848777c0-fc9c-4eab-ae07-5bad7f589707.png)

I was attempting to export the data from the Doppler voltage scan (run 40799 from 2022) to .csv. The included screenshot shows the error message shown in the terminal. Note that this is a 1n type run where we are scanning ILE2:DOPPLR instead of ILE2:BIAS15, in addition when visualizing the effect we use the asymmetry from the F/B counters instead of the neutral beam monitors.

**Comment by dfujim** [comment]
Resolved in 47a7eabaf2c13d414b14693cf60364ee60945933
