### ISSUE TITLE
name 'd' is not defined

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#115]
Possibly associated with bdata

Occurs on bfit version 4.20.4 (I have not observed this in previous versions of bfit and/or bdata)

Gives the entitled error message when attempting to plot or export the following runs:

2019: 45309
2019: 45312

And what appear to be many others from that same period.

**Comment by vkarner** [comment]
I have the same issue when trying to plot data from 2020. I think it probably has to do with the correction for the additional pre beam which occurred in low field data from around 2020.

**Comment by dfujim** [comment]
Fixed in bdata commit [2c5c2b1a0f764688a7fe8b06b9e1d78505396184](https://github.com/dfujim/bdata/commit/2c5c2b1a0f764688a7fe8b06b9e1d78505396184#diff-c8ccd2bbce72cc83bf373e0b68805c5d0e7d2a92c9b144d47763d3c1e82047b1L1727)
