### ISSUE TITLE
Issue with Plotting Combined Normalized SLR Spectra

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#116]
See, for example runs 2022#40711 and 2022#40666

The combined normalized spectra do not plot correctly either in the Inspect or Fetch tabs. 

Also possibly related to bdata? 

Issue seems to have arisen in a recent bfit update, although I am not aware of which one

**Comment by dfujim** [comment]
Seems to have been resolved from the changes in bdata [commit](https://github.com/dfujim/bdata/commit/2c5c2b1a0f764688a7fe8b06b9e1d78505396184#diff-c8ccd2bbce72cc83bf373e0b68805c5d0e7d2a92c9b144d47763d3c1e82047b1L1727)

Can you please confirm? Update to bdata v6.11.4
