### ISSUE TITLE
Issue with Modifying Parameters in Fit Tab Using "Initial Value"

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#119]
(see title)

**To Reproduce**
Steps to reproduce the behaviour:
1. Any 1f run
2. Go to fit tab
3. Open the "Initial Value" tab 
4. Attempt to move any of the initial parameters using the "sliders"
5. None of the parameters are adjustable as intended 

Appears to occur in versions 4.21.x and forward (works correctly on version 4.20.4)

**Comment by dfujim** [comment]
I think this is actually an issue with new versions of matplotlib... anyway it's seemingly fixed now. (c26a6cd410d57b4592b19fb25c8bbffa15c73aa0)
