### ISSUE TITLE
Significant Figures of Magnetic Field in Tesla

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#35]
Under the Fetch Data tab it shows a list of runs with the year, run number, temperature, magnetic field, implantation bias, etc. I am currently working on some low field data and the magnetic field is automatically converted from Gauss to Tesla. That is great, but my data at 150 G is showing up as 0.02 T. I think you need to increase the significant figures or change the way it is shown.

**Comment by dfujim** [comment]
Resolved in commit 13663114f5d323bca50e1ed56d1a21144320fa45
