### ISSUE TITLE
Ability to fit defined time range?

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#37]
Have you considered implementing the ability to fit a part of the time range? 

For example, sometimes I look at the first second of the data to get a good estimate of the initial asymmetry. I will do this specially if I am looking at a sample with a potential missing fraction.

**Comment by dfujim** [comment]
Is there a usage beyond this case? You could get the initial asymmetry just by zooming and looking by eye.

**Comment by vkarner** [comment]
In the case of a missing fraction what I would do is look at runs under the same conditions on samples measured before and after the one I am interested in. I fit the first second of all the different samples at room temperature to get an estimate of where the initial asymmetry would be if there was no missing fraction. That allows me to estimate the missing fraction.

**Comment by vkarner** [comment]
It also might be useful to people who do not want to include a background component and say want to fit from 0.5 seconds to 16 seconds.

**Comment by dfujim** [comment]
Hmm ok I see how this would be useful now.

**Comment by dfujim** [comment]
Added in a186e7a6bda47414d8e20d6bc16a0c944e5ff47e
