### ISSUE TITLE
Comb runs cannot be plotted while acquiring data if a non-comb run has been run prior

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#47]
This evening we noticed while switching between 1f and 1w runs that if a 1f run was acquired before the 1w run, then the 1w run will not plot while the data is acquiring. However, it can be plotted just fine once the data acquisition is finalized. The runs I noticed this on were: 2019: 40193.

**Comment by dfujim** [comment]
This is an issue with the DAQ. It is not easily resolvable in bfit.
