### ISSUE TITLE
Data and Fit Both Fail to Export .csv Files in Latest 4.X Update

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#77]
![Screenshot_100](https://user-images.githubusercontent.com/57420764/99493621-6b424a00-2924-11eb-87be-06e2294d6f3b.png)
![Screenshot_98](https://user-images.githubusercontent.com/57420764/99493633-709f9480-2924-11eb-9dc2-8541e02b5212.png)

**Comment by dfujim** [comment]
Resolved in 7f5b3e6b0317dcd263c2f550b9228e5089680d8b
