### ISSUE TITLE
Exported csv has different value of HV compared to bfit displayed value

### ISSUE THREAD

**Issue by ethoeng** [dfujim/bfit#83]
Hi Derek, 
I'm trying to process data offline by exporting the run number 45294 (year 2020). 
The high-voltage is displayed as 4 kV on bfit, but when I export this to csv it's changed to 8 kV.
Is there an issue with the exporting of the data ?
Or perhaps the wrong data is exported from bfit ?

Thanks,
Ed

**Comment by dfujim** [comment]
It seems to work for me. That being said, the title of the run says 8 kV, perhaps you're looking at that by mistake. To clarify output on your machine please run the following: 

```python
import pandas as pd

filename = "test.csv" # export file name here
df = pd.read_csv(filename, comment='#')
df[['Run Number', 'Platform Bias (kV)', 'Title']]
```
