### ISSUE TITLE
1n plotting defaults

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bfit#84]
In the GUI, 1n runs appear to use the NBM counters for their asymmetry calculation, without any means to <i>change</i> this behaviour. While this default is sensible when using <sup>8</sup>Li, it is detrimental when using other probes where the NBMs are not used (e.g., <sup>31</sup>Mg).

I think it would be a good idea to have a toggle allowing you to specify which counters you'd like to use. Better still (i.e., clearer and more explicit) would be to just have separate plotting options for both the NBM and NMR/NQR asymmetries (similar to bnmrfit).

**Comment by dfujim** [comment]
Hmm good point. I will amend this.

**Comment by dfujim** [comment]
Toggling 1n use of NBM is now possible from the old toggle in the menu bar. (1b378d595117622b43a42ed75918fffae704547d)

Note that you can choose which counters to use from Menu -> Settings -> Histograms
